import "@/styles/main.css";
import { LayoutProps } from "@/types/app";
import { poppins } from "@/ui/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang="en" className={`${poppins.variable}`}>
            <body className="font-poppins">{children}</body>
        </html>
    );
}
